apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: solver-operator
rules:
  - apiGroups:
      - ''
    resources:
      - pods
    verbs:
      - list
      - watch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - list
  - apiGroups:
      - instana.com
    resources:
      - demos
    verbs:
      - list
      - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solver-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: solver-operator
subjects:
  - kind: ServiceAccount
    name: solver-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: solver-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solver-operator
spec:
  selector:
    matchLabels:
      app: solver-operator
  replicas: 1
  template:
    metadata:
      labels:
        app: solver-operator
    spec:
      serviceAccountName: solver-operator
      containers:
        - image: docker.io/rsynek/solver-operator:1.0-SNAPSHOT
          name: solver-operator
          imagePullPolicy: IfNotPresent